### ISSUE TITLE
automatic compilation of mineSStuBs?

### ISSUE THREAD

**Issue by monperrus** [mast-group/mineSStuBs#1]
Hi,

It would be great to be able to simply compile mineSStuBs on the command-line.

What about adding a Maven or Gradle build script in the repo?

Thanks!

--Martin

**Comment by mpatsis** [comment]
Great idea!
I'll have a shot at this this weekend.

Regards,
Rafael

**Comment by mpatsis** [comment]
This was mostly a success with one exception. I could not find a Maven dependency for egit.github.core that worked. I am wondering if this has to do with my version of m2e in Eclipse.
I've just made a commit where added a pom.xml with the dependencies. For now the egit library will have to be included manually in build but you can find it in the lib folder.

**Comment by monperrus** [comment]
Thanks a lot for the progress.

Found https://repo.eclipse.org/content/unzip/snapshots.unzip and made further steps in #2

**Comment by monperrus** [comment]
Next question, what's the main method and how to use it?

**Comment by monperrus** [comment]
Making great progress with `mvn exec:java -Dexec.mainClass=uk.ac.ed.inf.mpatsis.sstubs.mining.SStuBsMiner -Dexec.args="projects ."`

**Comment by monperrus** [comment]
It works!
